# https://wiki.archlinux.org/title/Network_bridge
# https://wiki.archlinux.org/title/Linux_Containers
- name: netdev
  ansible.builtin.copy:
    src: files/br0.netdev
    dest: /etc/systemd/network/bro0.netdev
    owner: root
    group: root
    mode: '644'
  notify: restart systemd-networkd

- name: network
  ansible.builtin.copy:
    src: files/br0.network
    dest: /etc/systemd/network/bro0.network
    owner: root
    group: root
    mode: '644'
  notify: restart systemd-networkd
