- name: services directory
  ansible.builtin.file:
    path: /root/services/
    state: directory
    mode: '700'

- name: copy
  ansible.builtin.copy:
    src: pi-hole
    dest: /root/services/
    owner: root
    group: root
    mode: '700'

- name: etc-pihole volume
  ansible.builtin.file:
    path: /root/services/pi-hole/etc-pihole
    state: directory
    owner: '999'
    group: '999'
    mode: '755'

- name: run pi-hole
  ansible.builtin.shell: "cd /root/services/pi-hole && docker-compose down && docker-compose up -d"

- name: add pi-hole backup script to crontab
  ansible.builtin.cron:
    name: backup pi-hole
    minute: "01"
    hour: "2"
    user: root
    job: "/root/services/pi-hole/backup.sh > /dev/null 2>&1"
