- name: install gitlab runner package
  community.general.pacman:
    update_cache: yes
    name:
      - gitlab-runner
    state: present

- name: add gitlab-runner to docker group
  ansible.builtin.user:
    name: gitlab-runner
    groups: docker

- name: ensure gitlab-runner is started and enabled at boot
  ansible.builtin.systemd:
    name: gitlab-runner
    state: started
    enabled: yes
